### ISSUE TITLE
Memory overflow with regular .*

### ISSUE THREAD

**Issue by dragokas** [jpbro/VbPcre2#16] opened 2017-06-19 18:54 UTC
I found "infinite" loop in SubMatches method, when you are executing TestRegex2() with l_Regex = ".*$"

**Comment by dragokas** [comment] 2017-06-19 19:08
Another different infinite loop:

l_SubjectText = "Wyzo"
l_Regex = "(Manager)|^((copy of )?)"

**Comment by jpbro** [comment] 2017-06-19 20:30
Hi @dragokas, thanks for these examples. Looks like the problem is with the Global loop and PCRE2 empty match behaviour (PCRE2 can return an empty match, but the loop doesn't detect this properly and ends up looping infinitely). I will have a fix soon.

**Comment by jpbro** [comment] 2017-06-19 21:26
Just committed a partial solution for this problem. There should be no more infinite loop, but we're getting different results to VBScript CRegex when Multiline=True and there could be subsequent matches after an empty match. I'll need to work on a solution for this.

**Comment by jpbro** [comment] 2017-09-06 07:34
Closing this issue since I think it is fixed re: the infinite loop.

I'm opening a new issue to discuss the PCRE2/VBScript discrepancy described above: https://github.com/jpbro/VbPcre2/issues/19

**Closed as completed by jpbro** 2017-09-06 07:34 UTC
Labels: bug
